-- =========================
-- TABLE USERS
-- =========================
CREATE TABLE "users" (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    is_admin BOOLEAN NULL,
    is_super_admin BOOLEAN NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- USER INFORMATIONS
-- =========================
CREATE TABLE user_informations (
    user_informations_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NULL,
    last_name VARCHAR(255) NULL,
    street_name VARCHAR(255) NULL,
    street_name_add VARCHAR(255) NULL,
    house_number BIGINT NULL,
    postcode VARCHAR(255) NULL,
    city VARCHAR(255) NULL,
    country VARCHAR(255) NULL,
    phone VARCHAR(255) NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- USER ORDER INFORMATIONS
-- =========================
CREATE TABLE user_order_informations (
    user_order_informations_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_informations_id BIGINT,
    order_id BIGINT NOT NULL,
    name VARCHAR(255) NULL,
    last_name VARCHAR(255) NULL,
    street_name VARCHAR(255) NULL,
    street_name_add VARCHAR(255) NULL,
    house_number BIGINT NULL,
    postcode VARCHAR(255) NULL,
    city VARCHAR(255) NULL,
    country VARCHAR(255) NULL,
    phone VARCHAR(255) NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- COMPANY
-- =========================
CREATE TABLE company (
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NULL,
    siret VARCHAR(255) NULL,
    tva_number VARCHAR(255) NULL,
    legal_form VARCHAR(255) NULL,
    street_name VARCHAR(255) NULL,
    street_name_add VARCHAR(255) NULL,
    house_number VARCHAR(255) NULL,
    postcode VARCHAR(255) NULL,
    city VARCHAR(255) NULL,
    country VARCHAR(255) NULL,
    latitude FLOAT(53) NULL,
    longitude FLOAT(53) NULL,
    phone VARCHAR(255) NULL,
    email VARCHAR(255) NULL,
    website VARCHAR(255) NULL,
    logo_url VARCHAR(255) NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- USER_COMPANY
-- =========================
CREATE TABLE user_company (
    user_company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- EQUIPEMENT CATEGORY
-- =========================
CREATE TABLE equipement_category (
    equipement_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- EQUIPEMENT TYPE
-- =========================
CREATE TABLE equipement_type (
    equipement_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipement_category_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- EQUIPEMENT COMPANY
-- =========================
CREATE TABLE equipement_company (
    equipement_company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    equipement_type_id BIGINT NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NULL,
    price_per_day FLOAT(53) NOT NULL,
    stock BIGINT NOT NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- DOMAIN
-- =========================
CREATE TABLE domain (
    domain_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NULL,
    street_name VARCHAR(255) NULL,
    street_name_add VARCHAR(255) NULL,
    house_number BIGINT NULL,
    postcode VARCHAR(255) NULL,
    city VARCHAR(255) NULL,
    country VARCHAR(255) NULL,
    latitude FLOAT(53) NULL,
    longitude FLOAT(53) NULL,
    price_per_day FLOAT(53) NULL,
    capacity BIGINT NULL,
    image_url VARCHAR(255) NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- ORDERS
-- =========================
CREATE TABLE "orders" (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- ORDER STATUS
-- =========================
CREATE TABLE order_status (
    order_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- ORDER ITEM
-- =========================
CREATE TABLE order_item (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    equipement_company_id BIGINT NULL,
    domain_id BIGINT NULL,
    quantity BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    unit_price FLOAT(53) NOT NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- PAYMENT
-- =========================
CREATE TABLE payment (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    amount FLOAT(53) NOT NULL,
    payment_status_id BIGINT NOT NULL,
    provider VARCHAR(255) NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- PAYMENT STATUS
-- =========================
CREATE TABLE payment_status (
    payment_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- PAYOUT STATUS
-- =========================
CREATE TABLE payout_status (
    payout_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- COMPANY PAYOUT
-- =========================
CREATE TABLE company_payout (
    company_payout_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    amount FLOAT(53) NOT NULL,
    payout_status_id BIGINT NOT NULL,
    datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
    datetime_update DATE NULL,
    user_create_id BIGINT NULL,
    user_update_id BIGINT NULL
);

-- =========================
-- FOREIGN KEYS
-- =========================
ALTER TABLE user_informations ADD CONSTRAINT fk_user_info_user FOREIGN KEY (user_id) REFERENCES "users"(user_id);

ALTER TABLE user_order_informations ADD CONSTRAINT fk_user_order_info_user FOREIGN KEY (user_id) REFERENCES "users"(user_id);
ALTER TABLE user_order_informations ADD CONSTRAINT fk_user_order_info_order FOREIGN KEY (order_id) REFERENCES "orders"(order_id);
ALTER TABLE user_order_informations ADD CONSTRAINT fk_user_order_info_informations FOREIGN KEY (user_informations_id) REFERENCES user_informations(user_informations_id);

ALTER TABLE user_company ADD CONSTRAINT fk_user_company_user FOREIGN KEY (user_id) REFERENCES "users"(user_id);
ALTER TABLE user_company ADD CONSTRAINT fk_user_company_company FOREIGN KEY (company_id) REFERENCES company(company_id);

ALTER TABLE equipement_type ADD CONSTRAINT fk_equipement_type_category FOREIGN KEY (equipement_category_id) REFERENCES equipement_category(equipement_category_id);
ALTER TABLE equipement_company ADD CONSTRAINT fk_equipement_company_company FOREIGN KEY (company_id) REFERENCES company(company_id);
ALTER TABLE equipement_company ADD CONSTRAINT fk_equipement_company_type FOREIGN KEY (equipement_type_id) REFERENCES equipement_type(equipement_type_id);

ALTER TABLE domain ADD CONSTRAINT fk_domain_company FOREIGN KEY (company_id) REFERENCES company(company_id);

ALTER TABLE "orders" ADD CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES "users"(user_id);
ALTER TABLE "orders" ADD CONSTRAINT fk_orders_status FOREIGN KEY (status_id) REFERENCES order_status(order_status_id);

ALTER TABLE order_item ADD CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES "orders"(order_id);
ALTER TABLE order_item ADD CONSTRAINT fk_order_item_equipement FOREIGN KEY (equipement_company_id) REFERENCES equipement_company(equipement_company_id);
ALTER TABLE order_item ADD CONSTRAINT fk_order_item_domain FOREIGN KEY (domain_id) REFERENCES domain(domain_id);

ALTER TABLE payment ADD CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES "orders"(order_id);
ALTER TABLE payment ADD CONSTRAINT fk_payment_status FOREIGN KEY (payment_status_id) REFERENCES payment_status(payment_status_id);

ALTER TABLE company_payout ADD CONSTRAINT fk_company_payout_company FOREIGN KEY (company_id) REFERENCES company(company_id);
ALTER TABLE company_payout ADD CONSTRAINT fk_company_payout_order_item FOREIGN KEY (order_item_id) REFERENCES order_item(order_item_id);
ALTER TABLE company_payout ADD CONSTRAINT fk_company_payout_status FOREIGN KEY (payout_status_id) REFERENCES payout_status(payout_status_id);