import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1700000000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Create USERS table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "users" (
        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        login VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        password VARCHAR(255) NOT NULL,
        is_admin BOOLEAN NULL,
        is_super_admin BOOLEAN NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create USER_INFORMATIONS table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS user_informations (
        user_informations_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        name VARCHAR(255) NULL,
        last_name VARCHAR(255) NULL,
        street_name VARCHAR(255) NULL,
        street_name_add VARCHAR(255) NULL,
        house_number BIGINT NULL,
        postcode VARCHAR(255) NULL,
        city VARCHAR(255) NULL,
        country VARCHAR(255) NULL,
        phone VARCHAR(255) NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create USER_ORDER_INFORMATIONS table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS user_order_informations (
        user_order_informations_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        user_informations_id BIGINT,
        order_id BIGINT NOT NULL,
        name VARCHAR(255) NULL,
        last_name VARCHAR(255) NULL,
        street_name VARCHAR(255) NULL,
        street_name_add VARCHAR(255) NULL,
        house_number BIGINT NULL,
        postcode VARCHAR(255) NULL,
        city VARCHAR(255) NULL,
        country VARCHAR(255) NULL,
        phone VARCHAR(255) NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create COMPANY table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS company (
        company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        description VARCHAR(255) NULL,
        siret VARCHAR(255) NULL,
        tva_number VARCHAR(255) NULL,
        legal_form VARCHAR(255) NULL,
        street_name VARCHAR(255) NULL,
        street_name_add VARCHAR(255) NULL,
        house_number VARCHAR(255) NULL,
        postcode VARCHAR(255) NULL,
        city VARCHAR(255) NULL,
        country VARCHAR(255) NULL,
        latitude FLOAT(53) NULL,
        longitude FLOAT(53) NULL,
        phone VARCHAR(255) NULL,
        email VARCHAR(255) NULL,
        website VARCHAR(255) NULL,
        logo_url VARCHAR(255) NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create USER_COMPANY table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS user_company (
        user_company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        company_id BIGINT NOT NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create EQUIPEMENT_CATEGORY table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS equipement_category (
        equipement_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code VARCHAR(255) NOT NULL,
        name VARCHAR(255) NOT NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create EQUIPEMENT_TYPE table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS equipement_type (
        equipement_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        equipement_category_id BIGINT NOT NULL,
        name VARCHAR(255) NOT NULL,
        code VARCHAR(255) NOT NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create EQUIPEMENT_COMPANY table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS equipement_company (
        equipement_company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id BIGINT NOT NULL,
        equipement_type_id BIGINT NOT NULL,
        display_name VARCHAR(255) NOT NULL,
        description VARCHAR(255) NULL,
        price_per_day FLOAT(53) NOT NULL,
        stock BIGINT NOT NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create DOMAIN table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS domain (
        domain_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id BIGINT NOT NULL,
        name VARCHAR(255) NOT NULL,
        description VARCHAR(255) NULL,
        street_name VARCHAR(255) NULL,
        street_name_add VARCHAR(255) NULL,
        house_number BIGINT NULL,
        postcode VARCHAR(255) NULL,
        city VARCHAR(255) NULL,
        country VARCHAR(255) NULL,
        latitude FLOAT(53) NULL,
        longitude FLOAT(53) NULL,
        price_per_day FLOAT(53) NULL,
        capacity BIGINT NULL,
        image_url VARCHAR(255) NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create ORDERS table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "orders" (
        order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        status_id BIGINT NOT NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create ORDER_STATUS table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS order_status (
        order_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code VARCHAR(255) NOT NULL,
        name VARCHAR(255) NOT NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create ORDER_ITEM table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS order_item (
        order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT NOT NULL,
        equipement_company_id BIGINT NULL,
        domain_id BIGINT NULL,
        quantity BIGINT NOT NULL,
        start_date DATE NOT NULL,
        end_date DATE NOT NULL,
        unit_price FLOAT(53) NOT NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create PAYMENT table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS payment (
        payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT NOT NULL,
        amount FLOAT(53) NOT NULL,
        payment_status_id BIGINT NOT NULL,
        provider VARCHAR(255) NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create PAYMENT_STATUS table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS payment_status (
        payment_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code VARCHAR(255) NOT NULL,
        name VARCHAR(255) NOT NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create PAYOUT_STATUS table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS payout_status (
        payout_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code VARCHAR(255) NOT NULL,
        name VARCHAR(255) NOT NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Create COMPANY_PAYOUT table
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS company_payout (
        company_payout_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_id BIGINT NOT NULL,
        order_item_id BIGINT NOT NULL,
        amount FLOAT(53) NOT NULL,
        payout_status_id BIGINT NOT NULL,
        datetime_create DATE NOT NULL DEFAULT CURRENT_DATE,
        datetime_update DATE NULL,
        user_create_id BIGINT NULL,
        user_update_id BIGINT NULL
      )
    `);

    // Add Foreign Keys using DO blocks to handle duplicate constraints
    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE user_informations ADD CONSTRAINT fk_user_info_user FOREIGN KEY (user_id) REFERENCES "users"(user_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE user_order_informations ADD CONSTRAINT fk_user_order_info_user FOREIGN KEY (user_id) REFERENCES "users"(user_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE user_order_informations ADD CONSTRAINT fk_user_order_info_order FOREIGN KEY (order_id) REFERENCES "orders"(order_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE user_order_informations ADD CONSTRAINT fk_user_order_info_informations FOREIGN KEY (user_informations_id) REFERENCES user_informations(user_informations_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE user_company ADD CONSTRAINT fk_user_company_user FOREIGN KEY (user_id) REFERENCES "users"(user_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE user_company ADD CONSTRAINT fk_user_company_company FOREIGN KEY (company_id) REFERENCES company(company_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE equipement_type ADD CONSTRAINT fk_equipement_type_category FOREIGN KEY (equipement_category_id) REFERENCES equipement_category(equipement_category_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE equipement_company ADD CONSTRAINT fk_equipement_company_company FOREIGN KEY (company_id) REFERENCES company(company_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE equipement_company ADD CONSTRAINT fk_equipement_company_type FOREIGN KEY (equipement_type_id) REFERENCES equipement_type(equipement_type_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE domain ADD CONSTRAINT fk_domain_company FOREIGN KEY (company_id) REFERENCES company(company_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE "orders" ADD CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES "users"(user_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE "orders" ADD CONSTRAINT fk_orders_status FOREIGN KEY (status_id) REFERENCES order_status(order_status_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE order_item ADD CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES "orders"(order_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE order_item ADD CONSTRAINT fk_order_item_equipement FOREIGN KEY (equipement_company_id) REFERENCES equipement_company(equipement_company_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE order_item ADD CONSTRAINT fk_order_item_domain FOREIGN KEY (domain_id) REFERENCES domain(domain_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE payment ADD CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES "orders"(order_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE payment ADD CONSTRAINT fk_payment_status FOREIGN KEY (payment_status_id) REFERENCES payment_status(payment_status_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE company_payout ADD CONSTRAINT fk_company_payout_company FOREIGN KEY (company_id) REFERENCES company(company_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE company_payout ADD CONSTRAINT fk_company_payout_order_item FOREIGN KEY (order_item_id) REFERENCES order_item(order_item_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE company_payout ADD CONSTRAINT fk_company_payout_status FOREIGN KEY (payout_status_id) REFERENCES payout_status(payout_status_id);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
      $$;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Drop foreign keys first
    await queryRunner.query(`ALTER TABLE company_payout DROP CONSTRAINT IF EXISTS fk_company_payout_status`);
    await queryRunner.query(`ALTER TABLE company_payout DROP CONSTRAINT IF EXISTS fk_company_payout_order_item`);
    await queryRunner.query(`ALTER TABLE company_payout DROP CONSTRAINT IF EXISTS fk_company_payout_company`);
    await queryRunner.query(`ALTER TABLE payment DROP CONSTRAINT IF EXISTS fk_payment_status`);
    await queryRunner.query(`ALTER TABLE payment DROP CONSTRAINT IF EXISTS fk_payment_order`);
    await queryRunner.query(`ALTER TABLE order_item DROP CONSTRAINT IF EXISTS fk_order_item_domain`);
    await queryRunner.query(`ALTER TABLE order_item DROP CONSTRAINT IF EXISTS fk_order_item_equipement`);
    await queryRunner.query(`ALTER TABLE order_item DROP CONSTRAINT IF EXISTS fk_order_item_order`);
    await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT IF EXISTS fk_orders_status`);
    await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT IF EXISTS fk_orders_user`);
    await queryRunner.query(`ALTER TABLE domain DROP CONSTRAINT IF EXISTS fk_domain_company`);
    await queryRunner.query(`ALTER TABLE equipement_company DROP CONSTRAINT IF EXISTS fk_equipement_company_type`);
    await queryRunner.query(`ALTER TABLE equipement_company DROP CONSTRAINT IF EXISTS fk_equipement_company_company`);
    await queryRunner.query(`ALTER TABLE equipement_type DROP CONSTRAINT IF EXISTS fk_equipement_type_category`);
    await queryRunner.query(`ALTER TABLE user_company DROP CONSTRAINT IF EXISTS fk_user_company_company`);
    await queryRunner.query(`ALTER TABLE user_company DROP CONSTRAINT IF EXISTS fk_user_company_user`);
    await queryRunner.query(`ALTER TABLE user_order_informations DROP CONSTRAINT IF EXISTS fk_user_order_info_informations`);
    await queryRunner.query(`ALTER TABLE user_order_informations DROP CONSTRAINT IF EXISTS fk_user_order_info_order`);
    await queryRunner.query(`ALTER TABLE user_order_informations DROP CONSTRAINT IF EXISTS fk_user_order_info_user`);
    await queryRunner.query(`ALTER TABLE user_informations DROP CONSTRAINT IF EXISTS fk_user_info_user`);

    // Drop tables
    await queryRunner.query(`DROP TABLE IF EXISTS company_payout`);
    await queryRunner.query(`DROP TABLE IF EXISTS payout_status`);
    await queryRunner.query(`DROP TABLE IF EXISTS payment_status`);
    await queryRunner.query(`DROP TABLE IF EXISTS payment`);
    await queryRunner.query(`DROP TABLE IF EXISTS order_item`);
    await queryRunner.query(`DROP TABLE IF EXISTS order_status`);
    await queryRunner.query(`DROP TABLE IF EXISTS "orders"`);
    await queryRunner.query(`DROP TABLE IF EXISTS domain`);
    await queryRunner.query(`DROP TABLE IF EXISTS equipement_company`);
    await queryRunner.query(`DROP TABLE IF EXISTS equipement_type`);
    await queryRunner.query(`DROP TABLE IF EXISTS equipement_category`);
    await queryRunner.query(`DROP TABLE IF EXISTS user_company`);
    await queryRunner.query(`DROP TABLE IF EXISTS company`);
    await queryRunner.query(`DROP TABLE IF EXISTS user_order_informations`);
    await queryRunner.query(`DROP TABLE IF EXISTS user_informations`);
    await queryRunner.query(`DROP TABLE IF EXISTS "users"`);
  }
}
